fragment animeInfo on Anime {
    id
    title {
        romaji
        english
    }
    format
    season
    year
    images {
        edges {
            node {
                facet
                link
            }
        }
    }
}

fragment animeThemeInfo on AnimeTheme {
    id
    slug
    type
    sequence
    song {
        id
        title {
            romaji
        }
        performances(first: 100) {
            ...performanceInfo
        }
    }
    group {
        name
    }
}

fragment performanceInfo on Performance {
    alias
    as
    artist {
        ...artistInfo
    }
    member {
        ...artistInfo
    }
    memberAlias
}

fragment artistInfo on Artist {
    id
    name {
        main
    }
    slug
}

fragment animeThemeEntryInfo on AnimeThemeEntry {
    id
    episodes
    notes
    nsfw
    spoiler
    version
}

fragment animeThemeVideoInfo on Video {
    id
    lyrics
    nc
    overlap
    resolution
    source
    subbed
    uncen
    tags
    link
}